version: '3' # vs mais atual

services: 

  # Emulador
  serve: 
    build: serve
    container_name: ro-ragnarok-serve
    restart: always
    tty: true
    working_dir: /rathena
    # SEMPRE QUE REINICIAR O CONTAINER IRAR BUIDAR O EMULADOR  
    volumes:
      # LEMBRAR SUBISTITUIR O NOME <EMULADOR> PARA A PASTE DO SEU SERVER
      - ./serve/rathena:/rathena
    # entrypoint: ./entrypoint.sh
    # TESTAR UM HEXED
    # command: >
    #   bash -c ./configure && make clean && make sql
    ports:
      - "5121:5121"
      - "6121:6121"
      - "6900:6900"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REDIRECT_STATUS=true
    networks:
      - ragnarok-app-network
    depends_on: 
      - db
      
  db:
    build: db
    container_name: ro-ragnarok-db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db/dbdata:/var/lib/mysql
      - ./db/sql-files:/docker-entrypoint-initdb.d
      # - ./db/log:/var/log/mysql
    environment:
      - MYSQL_DATABASE=ragnarok
      - MYSQL_ROOT_PASSWORD=R00t+
      - MYSQL_USER=ragnarok
      - MYSQL_PASSWORD=ragnarok
    networks:
      - ragnarok-app-network

  files:
    build: files
    container_name: ro-ragnarok-files
    restart: always
    tty: true
    working_dir: /files
    volumes:
      - ./files:/files
    # command: npm i && npm start
    ports:
      - "5737:5737"
    networks:
      - ragnarok-app-network

  ip:
    build: ip
    container_name: update-public-ip
    restart: always
    tty: true
    working_dir: /public-ip
    volumes:
      - ./ip:/public-ip
    networks:
      - ragnarok-app-network

  wsproxy:
    # image: node:18
    build: wsproxy
    container_name: ro-browser-wsproxy
    restart: always
    tty: true
    # command: >
    #   bash -c wsproxy -a 127.0.0.1:6900,127.0.0.1:6121,127.0.0.1:5121
    command: >
      bash -c wsproxy -a serve:6900,serve:6121,serve:5121
    ports:
      - "5999:5999"
    networks:
      - ragnarok-app-network
    depends_on:
      - serve
      - game
      - files

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      # 8080 is the host port and 80 is the docker port
      - "9000:80"
    environment:
      - PMA_ARBITRARY:1
      - PMA_HOST:db
      - MYSQL_USERNAME:ragnarok
      - MYSQL_ROOT_PASSWORD:ragnarok
    depends_on: 
      - db
    networks:
      - ragnarok-app-network
                        
networks:
  ragnarok-app-network:
    driver: host
